name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Vérifier les fichiers
        run: |
          test -f bash-linux/index.html
          test -f bash-linux/js/script.js
          echo "Les fichiers existent !"
