name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le projet
        uses: actions/checkout@v4

      - name: Démarrer Docker
        run: docker compose -f cours_docker/docker-compose.yml up -d --build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      - name: Vérifier les conteneurs
        run: docker compose ps

      - name: Tester l'application
        run: curl http://localhost:3000/health

      - name: Arrêter Docker
        if: always()
        run: docker compose -f cours_docker/docker-compose.yml down

      - name: Vérifier les fichiers
        run: |
          test -f bash-linux/index.html
          test -f bash-linux/js/script.js
          echo "Les fichiers existent !"
